version: '3.8'

services:
  web:
    build: ..
    command: gunicorn --bind 0.0.0.0:8000 photo_api.wsgi
    volumes:
      - .:/app
      - static_volume:/app/static
      - ./media:/app/media
    ports:
      - "8000:8000"

volumes:
  static_volume:
  media_volume: